### ISSUE TITLE
KeyError while reading BAM

### ISSUE THREAD

**Issue by boboppie** [xryanglab/RiboCode#18]
Dear developers,

I'm having the following error message:

```        Reading bam file: Aligned.toTranscriptome.out.bam......
Traceback (most recent call last):
  File "/home/huf/.local/bin/RiboCode", line 11, in <module>
    sys.exit(main())
  File "/home/huf/.local/lib/python2.7/site-packages/RiboCode/RiboCode.py", line 40, in main
    tpsites_sum, total_psites_number = process_bam.psites_count(configIn.configList,transcript_dict,thread_num=1)
  File "/home/huf/.local/lib/python2.7/site-packages/RiboCode/process_bam.py", line 111, in psites_count
    tpsites_sum,total_psites_number = read_bam(configList[0])
  File "/home/huf/.local/lib/python2.7/site-packages/RiboCode/process_bam.py", line 77, in read_bam
    tpsites[tid][t_psite] += 1
KeyError: 'ENSMUST00000035606.8'
```

I even sorted the bam, but it gave me the same error for a different transcript Id. Do you know where possibly goes wrong?

Best wishes,
Fengyuan

**Comment by xzt41** [comment]
Hi, this error means the transcript id "ENSMUST00000035606.8" is not in the GTF file or annotation file generated by “prepare_transcripts.py”. Make sure it can be found in the gtf file (grep ENSMUST00000035606.8 your_gtf_file).

**Comment by boboppie** [comment]
Dear @xzt41 ,

Thank you for the reply. Yes, it seems I messed up my annotation.
