### ISSUE TITLE
Error in <Preparing the transcripts annotation files> step

### ISSUE THREAD

**Issue by yuechaowu** [xryanglab/RiboCode#22]
ribocode was installed by conda and run in python2.7 env.
when i run this command `prepare_transcripts -g ~/data/reference/IRGSP/IRGSP.gtf -f ~/data/reference/IRGSP/IRGSP.fa -o annotation/`

**then i get fellow error:**
Traceback (most recent call last):
  File "/home/wuyuechao/data/bio-tools/anaconda3/envs/ribocode/bin/prepare_transcripts", line 10, in <module>
    sys.exit(main())
  File "/home/wuyuechao/data/bio-tools/anaconda3/envs/ribocode/lib/python2.7/site-packages/RiboCode/prepare_transcripts.py", line 388, in main
    processTranscripts(args.genomeFasta,args.gtfFile,args.out_dir)
  File "/home/wuyuechao/data/bio-tools/anaconda3/envs/ribocode/lib/python2.7/site-packages/RiboCode/prepare_transcripts.py", line 311, in processTranscripts
    genomic_seq = GenomeSeq(genomeFasta)
  File "/home/wuyuechao/data/bio-tools/anaconda3/envs/ribocode/lib/python2.7/site-packages/RiboCode/prepare_transcripts.py", line 205, in __init__
    self.fh = Fasta(filename, key_fn = get_chrom)
  File "/home/wuyuechao/data/bio-tools/anaconda3/envs/ribocode/lib/python2.7/site-packages/pyfasta/fasta.py", line 73, in __init__
    flatten_inplace)
  File "/home/wuyuechao/data/bio-tools/anaconda3/envs/ribocode/lib/python2.7/site-packages/pyfasta/records.py", line 48, in prepare
    idx = cPickle.load(fh)
ValueError: unsupported pickle protocol: 4

please help thx!

**Comment by yuechaowu** [comment]
in my situation,need create an new conda env  and definite python version
`conda create -n ribocode python=3.5`
`conda activate ribocode`
`conda install ribocode`
error is solved:)
