### ISSUE TITLE
can't locate attribute: psites_number

### ISSUE THREAD

**Issue by trum994** [xryanglab/RiboCode#40]
I'm trying to debug a workflow that runs RiboCode. I tried using the latest container from quay.io and this is the error I'm running into. Any guidance on what I should look into first?

> 	Loading transcripts.pickle ...
> 	Loading Psites from xxxxx.transcriptome.dedup......
> _psites.hd5Traceback (most recent call last):
>   File "/usr/local/bin/RiboCode", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/RiboCode/RiboCode.py", line 40, in main
>     tpsites_sum, total_psites_number = process_bam.psites_count(configIn.configList,transcript_dict,thread_num=1)
>   File "/usr/local/lib/python3.9/site-packages/RiboCode/process_bam.py", line 107, in psites_count
>     tpsites_sum,total_psites_number = read_bam(configList[0])
>   File "/usr/local/lib/python3.9/site-packages/RiboCode/process_bam.py", line 45, in read_bam
>     tpsites,psites_number = load_psites(name + "_psites.hd5" )
>   File "/usr/local/lib/python3.9/site-packages/RiboCode/process_bam.py", line 31, in load_psites
>     psites_number = fin.attrs["psites_number"]
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "/usr/local/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
>     attr = h5a.open(self._id, self._e(name))
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
>   File "h5py/h5a.pyx", line 80, in h5py.h5a.open
> KeyError: "Can't open attribute (can't locate attribute: 'psites_number')"

**Comment by zhengtaoxiao** [comment]
Hi, have you solved this issue?
