### ISSUE TITLE
RiboCode_onestep crashes when calling detectORF

### ISSUE THREAD

**Issue by trum994** [xryanglab/RiboCode#41]
When trying to use RiboCode_onestep I come across this error below:

> Finished reading bam file!
> Traceback (most recent call last):
>   File "/usr/local/bin/RiboCode_onestep", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/RiboCode/RiboCode_onestep.py", line 76, in main
>     detectORF.main(gene_dict=gene_dict, transcript_dict=transcript_dict, annot_dir = "annot",
> TypeError: main() missing 3 required positional arguments: 'dependence_test', 'stouffer_adj', and 'pval_adj'

My command line looks like this:
`Singularity> RiboCode_onestep -g Homo_sapiens.GRCh38.104.gtf -f Homo_sapiens.GRCh38.dna.primary_assembly.fa -r my.transcriptome.dedup.bam -l no -o RiboCode_ORFs_result`

**Comment by zhengtaoxiao** [comment]
Thank you for pointing this out. I have fixed it.
