### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'NoneType'

### ISSUE THREAD

**Issue by LiTing99-cutie** [xryanglab/RiboCode#48]
When i used metaplots -a RiboCode_annot -r HEK293Aligned.toTranscriptome.out.bam, an error occurred:
[2022-07-28 21:05:31] Create metaplot file and predict the P-site locations ...
        Loading transcripts.pickle ...
Traceback (most recent call last):
  File "/home/user/BGM/lit/anaconda3/envs/ribocode/bin/metaplots", line 10, in <module>
    sys.exit(main())
  File "/home/user/BGM/lit/anaconda3/envs/ribocode/lib/python3.7/site-packages/RiboCode/metaplots.py", line 241, in main
    meta_analysis(gene_dict,transcript_dict,args)
  File "/home/user/BGM/lit/anaconda3/envs/ribocode/lib/python3.7/site-packages/RiboCode/metaplots.py", line 181, in meta_analysis
    filter_tids = filter_transcript(gene_dict,transcript_dict)
  File "/home/user/BGM/lit/anaconda3/envs/ribocode/lib/python3.7/site-packages/RiboCode/metaplots.py", line 48, in filter_transcript
    level = list(sorted(levels))[0]
TypeError: '<' not supported between instances of 'str' and 'NoneType'
how can i solve this? thanx!!

**Comment by LiTing99-cutie** [comment]
Thanks for your kindly reply, it works now!

**Comment by zyd1946** [comment]
> I have fixed this issue in the new release v.1.2.15.

I got the same error but could not find the release v.1.2.15
