### ISSUE TITLE
ValueError: unsupported pickle protocol: 5 in metaplots 

### ISSUE THREAD

**Issue by z626093820** [xryanglab/RiboCode#54]
**when i use the metaplots function of ribocode 1.2.14， it show the error:, how can i slove it ,thank you in advance!!!**

Create metaplot file and predict the P-site locations ...
        Loading transcripts.pickle ...
Traceback (most recent call last):
  File "/home/zuozd/miniconda3/envs/ribocode/bin/metaplots", line 10, in <module>
    sys.exit(main())
  File "/home/zuozd/miniconda3/envs/ribocode/lib/python3.7/site-packages/RiboCode/metaplots.py", line 241, in main
    gene_dict,transcript_dict = load_transcripts_pickle(os.path.join(args.annot_dir,"transcripts.pickle"))
  File "/home/zuozd/miniconda3/envs/ribocode/lib/python3.7/site-packages/RiboCode/prepare_transcripts.py", line 293, in load_transcripts_pickle
    gene_dict, transcript_dict = pickle.load(fin)
ValueError: unsupported pickle protocol: 5

**Comment by zhengtaoxiao** [comment]
I guess you might create the pickle file using a low version of Python and load it in a new version of Python. Please try to remove the pickle and perform the ribocode analysis from scratch.
