### ISSUE TITLE
prepare_transcripts failed

### ISSUE THREAD

**Issue by manishbiotechie** [xryanglab/RiboCode#9]
Traceback (most recent call last):
  File "/home/dr/anaconda2/bin/prepare_transcripts", line 10, in <module>
    sys.exit(main())
  File "/home/dr/anaconda2/lib/python2.7/site-packages/RiboCode/prepare_transcripts.py", line 388, in main
    processTranscripts(args.genomeFasta,args.gtfFile,args.out_dir)
  File "/home/dr/anaconda2/lib/python2.7/site-packages/RiboCode/prepare_transcripts.py", line 308, in processTranscripts
    gene_dict,transcript_dict = readGTF(gtfFile)
  File "/home/dr/anaconda2/lib/python2.7/site-packages/RiboCode/prepare_transcripts.py", line 187, in readGTF
    gene => transcript => exon (or CDS)" % i)
RiboCode.prepare_transcripts.ParsingError: Error in line 0. The annotation in GTF file should be three-level hierarchy of 					                    gene => transcript => exon (or CDS)

I am getting this error and I am new to bioinformatics kindly resolve....

**Comment by xzt41** [comment]
Hi, it looks like the annotations in your GTF file are not complete, it should include three-level hierarchy annotations: genes,transcripts and exons. You can add the missing annotations by using the "GTFupdate" command in RiboCode. Please refer to [GTF_update.rst](https://github.com/xryanglab/RiboCode/blob/master/data/GTF_update.rst) for more information.

**Comment by Udaykage** [comment]
I also got the same error and i use GTFupdate command and i got a error saying 

Traceback (most recent call last):
  File "/apps/python/3.7.2/bin/GTFupdate", line 11, in <module>
    load_entry_point('RiboCode==1.2.11', 'console_scripts', 'GTFupdate')()
  File "/apps/python/3.7.2/lib/python3.7/site-packages/RiboCode/GTF_update.py", line 117, in main
    gset,sourted_gset_keys = GroupGeneSubsets(args.gtfFile)
  File "/apps/python/3.7.2/lib/python3.7/site-packages/RiboCode/GTF_update.py", line 50, in GroupGeneSubsets
    chrom,gid,strand = i.split(":")
ValueError: too many values to unpack (expected 3)



Appreciate your help.
Thanks

**Comment by yannnnLi** [comment]
> I also got the same error and i use GTFupdate command and i got a error saying
> 
> Traceback (most recent call last):
> File "/apps/python/3.7.2/bin/GTFupdate", line 11, in
> load_entry_point('RiboCode==1.2.11', 'console_scripts', 'GTFupdate')()
> File "/apps/python/3.7.2/lib/python3.7/site-packages/RiboCode/GTF_update.py", line 117, in main
> gset,sourted_gset_keys = GroupGeneSubsets(args.gtfFile)
> File "/apps/python/3.7.2/lib/python3.7/site-packages/RiboCode/GTF_update.py", line 50, in GroupGeneSubsets
> chrom,gid,strand = i.split(":")
> ValueError: too many values to unpack (expected 3)
> 
> Appreciate your help.
> Thanks

I also got the same error when I updated my GTF file.

Traceback (most recent call last):
  File "/public/home/yliang/miniconda3/envs/ribocode/bin/GTFupdate", line 10, in <module>
    sys.exit(main())
  File "/public/home/yliang/miniconda3/envs/ribocode/lib/python2.7/site-packages/RiboCode/GTF_update.py", line 117, in main
    gset,sourted_gset_keys = GroupGeneSubsets(args.gtfFile)
  File "/public/home/yliang/miniconda3/envs/ribocode/lib/python2.7/site-packages/RiboCode/GTF_update.py", line 50, in GroupGeneSubsets
    chrom,gid,strand = i.split(":")
ValueError: too many values to unpack
